### ISSUE TITLE
ANSI C refactoring and adding GNUmakefile

### ISSUE THREAD

**Issue by serfcity** [wibyweb/wiby#10]
What do you think about refactoring your code in ANSI C under [GNU Coding Standards](https://www.gnu.org/prep/standards/standards.html) code-style?
(So, I can do it)

This is very interesting project!

Also I suppose, that adding GNUmakefile is no bad idea.

**Comment by wibyweb** [comment]
Not ready to do this yet, but thank you for reaching out.
