### ISSUE TITLE
Incorect characters in search results

### ISSUE THREAD

**Issue by yagarea** [wibyweb/wiby#11]
Example: When I look for this site: https://www.karlin.mff.cuni.cz/~zemlicka/
I see this in results:
![image](https://github.com/wibyweb/wiby/assets/14349169/ac3d9e7b-409c-4ac8-ae90-cd01f6af01b8)

There is `Jan ?emli?ka` instead of `Jan Žemlička`. I think this is encoding issue in wibys database.

**Comment by wibyweb** [comment]
Added the missing charset. Is working on that URL now. The crawler will eventually update any other pages using it.
