### ISSUE TITLE
Add ability to filter by domain

### ISSUE THREAD

**Issue by yagarea** [wibyweb/wiby#12]
I would love to have a feature where I can filter sites by domain. For example I would like to search for cats on sites with `.cz` domain

I tried this:
- [wiby.org/?q=site%3Acz](http://wiby.org/?q=site%3Acz) - this returns `.pl` site as second result
- [wiby.org/?q=site%3A.cz](http://wiby.org/?q=site%3A.cz) - this does not find anything

---
I suggest this syntax:
```
cat dom:cz
```
to search within specific domain.

**Comment by wibyweb** [comment]
I'm filing this under "nice to have features for the future" but it's not something I'll be able to work on right now.

**Comment by yagarea** [comment]
Understandable, thank you for your answer.
