### ISSUE TITLE
Invalid HTML standard

### ISSUE THREAD

**Issue by serfcity** [wibyweb/wiby#14]
You use `<!DOCTYPE html>` instead of `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">`

https://validator.w3.org/nu/?doc=http%3A%2F%2Fwiby.org%2F

But anyway, you have a lot of HTML errors: https://validator.w3.org/check?uri=http%3A%2F%2Fwiby.org&charset=%28detect+automatically%29&doctype=HTML+4.01+Transitional&group=0

**Comment by wibyweb** [comment]
I am aware there are some formatting issues, although it's been working fine up to now. Leaving as is. Will consider circling back to it at some point.
