### ISSUE TITLE
https://wiby.org/json/ can return malformed json (special chars?)

### ISSUE THREAD

**Issue by xpufx** [wibyweb/wiby#2]
As reported on the searxng github ( https://github.com/searxng/searxng/issues/1838 ) if the wiby result includes invalid(?) chars the json produced will be malformed.

https://wiby.org/json/?q=alsls+safdasd+search+fdlsala

Error is at this line: 

`    "Snippet": " Best New Search Engine – Virus Prevention – Safe Search Safe l e Best New Search Engine     Attention!   ¡Atención!   Atenç",
`

I am not sure if some sort of sanitation is possible or one would expect json to not break in the first place but posting it here for comment.

**Comment by wibyweb** [comment]
I am looking into a fix for this. Thanks for reporting.

**Comment by wibyweb** [comment]
Fix has been applied. Appears to be working *knock on wood*.

**Comment by xpufx** [comment]
@wibyweb Thank you.
