### ISSUE TITLE
Have I been banned from wiby.me?

### ISSUE THREAD

**Issue by cacharle** [wibyweb/wiby#4]
I can't reach wiby.me from my regular home connection but it works fine with my 4G, have I been banned somehow?

I have an instance of [searx](https://searx.github.io/searx/) through which I query wiby, could this be why I got banned?

I really like this project so I'd really like to be able to access it again

**Comment by wibyweb** [comment]
Hi, there is a botnet of tens of thousands of IP's sending false requests to the server every day. The IP's change regularly. Its possible your instance somehow got caught up in that (friendly fire). I might have to further refine my ban methods.  If you don't mind privately sending me the IP of your searx instance through wiby.me/feedback I can try unbanning it later today.

**Comment by cacharle** [comment]
Ok it's done, ty for your response 😃

**Comment by wibyweb** [comment]
Give it a try again.  I don't see your IP in my ban list. I had cleared out a ton of old banned IP's over the weekend so yours was probably unbanned by that time.

**Comment by cacharle** [comment]
I can access it again, ty!
